/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//Mahmoud Ali Ahmed Abd Elkhaliq 12200271
//Norhan Hussin Esmaiel 12200197
//Ebtehal Atef Mohamed 12200379 
//Esraa Salem Faisal 12200185 
//Habeba Abdelhady Abdelfatah 12200455
package videoplayer;

import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Mahmoud
 */
public class VideoPlayerGUI extends javax.swing.JFrame {
    
    /**
     * Creates new form VideoPlayerGUI
     */
    public VideoPlayerGUI() {
        initComponents();
        get_data();
    }
    
    public static Object UpdateWhere;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        TitlePanel = new javax.swing.JPanel();
        TitleLable = new javax.swing.JLabel();
        DeleteVideobut = new javax.swing.JButton();
        Chose_Category = new javax.swing.JLabel();
        AddVideolab = new javax.swing.JLabel();
        addVideobut = new javax.swing.JButton();
        DeleteVideolab = new javax.swing.JLabel();
        UpdateVid = new javax.swing.JButton();
        action_Choos = new javax.swing.JComboBox<>();
        UpdateVideolab = new javax.swing.JLabel();
        Search_Team = new javax.swing.JButton();
        Search_Player = new javax.swing.JButton();
        Search_Player_Field = new javax.swing.JTextField();
        Search_Team_Field = new javax.swing.JTextField();
        Search_By_PlayerLab = new javax.swing.JLabel();
        Search_By_TeamLab = new javax.swing.JLabel();
        Scroll_Videos_Table = new javax.swing.JScrollPane();
        Videos_Table = new javax.swing.JTable();
        Close_Lab = new javax.swing.JLabel();
        Refresh = new javax.swing.JButton();
        PlayLab = new javax.swing.JLabel();
        AtoZsort = new javax.swing.JLabel();
        sortZtoA = new javax.swing.JLabel();
        SortLab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainPanel.setBackground(new java.awt.Color(51, 51, 51));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitlePanel.setBackground(java.awt.Color.red);
        TitlePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        TitlePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitleLable.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        TitleLable.setForeground(new java.awt.Color(255, 255, 255));
        TitleLable.setText("World Cup Highlights");
        TitlePanel.add(TitleLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 200, 50));

        MainPanel.add(TitlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 50));

        DeleteVideobut.setBackground(new java.awt.Color(51, 51, 51));
        DeleteVideobut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/videoplayer/delete.png"))); // NOI18N
        DeleteVideobut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteVideobutActionPerformed(evt);
            }
        });
        MainPanel.add(DeleteVideobut, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 30, 30));

        Chose_Category.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Chose_Category.setForeground(new java.awt.Color(255, 255, 255));
        Chose_Category.setText(" Chose Category");
        MainPanel.add(Chose_Category, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 140, 20));

        AddVideolab.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        AddVideolab.setForeground(new java.awt.Color(255, 255, 255));
        AddVideolab.setText("Add Video");
        MainPanel.add(AddVideolab, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 80, 30));

        addVideobut.setBackground(new java.awt.Color(51, 51, 51));
        addVideobut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/videoplayer/plus.png"))); // NOI18N
        addVideobut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVideobutActionPerformed(evt);
            }
        });
        MainPanel.add(addVideobut, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 30, 30));

        DeleteVideolab.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        DeleteVideolab.setForeground(new java.awt.Color(255, 255, 255));
        DeleteVideolab.setText("Delete Video");
        MainPanel.add(DeleteVideolab, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 30));

        UpdateVid.setBackground(new java.awt.Color(51, 51, 51));
        UpdateVid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/videoplayer/updated.png"))); // NOI18N
        UpdateVid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateVidActionPerformed(evt);
            }
        });
        MainPanel.add(UpdateVid, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 30, 30));

        action_Choos.setFont(new java.awt.Font("Segoe UI Black", 3, 12)); // NOI18N
        action_Choos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Category", "Goal", "Attempt", "Amazing ball", "Red card", "Yellow card", "Foul", "VAR check", "Penalty" }));
        action_Choos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                action_ChoosActionPerformed(evt);
            }
        });
        MainPanel.add(action_Choos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 140, -1));

        UpdateVideolab.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        UpdateVideolab.setForeground(new java.awt.Color(255, 255, 255));
        UpdateVideolab.setText("Updarte Video");
        MainPanel.add(UpdateVideolab, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, 30));

        Search_Team.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Search_Team.setText("search");
        Search_Team.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_TeamActionPerformed(evt);
            }
        });
        MainPanel.add(Search_Team, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, -1));

        Search_Player.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Search_Player.setText("search");
        Search_Player.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_PlayerActionPerformed(evt);
            }
        });
        MainPanel.add(Search_Player, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));
        MainPanel.add(Search_Player_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 140, -1));
        MainPanel.add(Search_Team_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 140, -1));

        Search_By_PlayerLab.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Search_By_PlayerLab.setForeground(new java.awt.Color(255, 255, 255));
        Search_By_PlayerLab.setText("Search By Player");
        MainPanel.add(Search_By_PlayerLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 140, 20));

        Search_By_TeamLab.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Search_By_TeamLab.setForeground(new java.awt.Color(255, 255, 255));
        Search_By_TeamLab.setText("Search By Team");
        MainPanel.add(Search_By_TeamLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 140, 20));

        Videos_Table.setBackground(new java.awt.Color(51, 51, 51));
        Videos_Table.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Videos_Table.setForeground(new java.awt.Color(255, 255, 255));
        Videos_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Video Name", "Path", "Category", "Player", "Home Team", "Away Team"
            }
        )
        {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        }
    );
    Videos_Table.setGridColor(new java.awt.Color(102, 102, 102));
    Videos_Table.setRowHeight(30);
    Videos_Table.getTableHeader().setReorderingAllowed(false);
    Videos_Table.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            Videos_TableMouseClicked(evt);
        }
    });
    Scroll_Videos_Table.setViewportView(Videos_Table);

    MainPanel.add(Scroll_Videos_Table, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 67, 800, 360));

    Close_Lab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/videoplayer/close.png"))); // NOI18N
    Close_Lab.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            Close_LabMouseClicked(evt);
        }
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            Close_LabMouseEntered(evt);
        }
    });
    MainPanel.add(Close_Lab, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 30, 30));

    Refresh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    Refresh.setText("Refresh");
    Refresh.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            RefreshActionPerformed(evt);
        }
    });
    MainPanel.add(Refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, -1, -1));

    PlayLab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/videoplayer/play.png"))); // NOI18N
    PlayLab.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            PlayLabMouseClicked(evt);
        }
    });
    MainPanel.add(PlayLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 460, 60, 70));

    AtoZsort.setIcon(new javax.swing.ImageIcon(getClass().getResource("/videoplayer/sort-az.png"))); // NOI18N
    AtoZsort.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            AtoZsortMouseClicked(evt);
        }
    });
    MainPanel.add(AtoZsort, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, 50));

    sortZtoA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/videoplayer/sort-za.png"))); // NOI18N
    sortZtoA.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            sortZtoAMouseClicked(evt);
        }
    });
    MainPanel.add(sortZtoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, 50));

    SortLab.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
    SortLab.setForeground(new java.awt.Color(255, 255, 255));
    SortLab.setText("Sort :");
    MainPanel.add(SortLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 50, 50));

    getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 550));

    setSize(new java.awt.Dimension(992, 549));
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteVideobutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteVideobutActionPerformed
        // TODO add your handling code here:
        //Linkedlist.ls.remove(Videos_Table.getSelectedRow());
        Object Path = Videos_Table.getValueAt(Videos_Table.getSelectedRow(), 1);
        Link.LS.remove((String)Path);
        try{
            //call jdbc
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            //create connection
            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=videos;user=mahmoudd;password=123456");
            Statement stm = con.createStatement();
            stm.executeUpdate("DELETE FROM Video WHERE P = '"+Path+"';");
                
            //Show Successful Message
            JOptionPane.showMessageDialog(null, "DELETED Successfuly");
            //disconnect with database
            con.close();
        }catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        }
        catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_DeleteVideobutActionPerformed

    private void addVideobutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVideobutActionPerformed
        // TODO add your handling code here:
        AddFrame add = new AddFrame();
        add.setVisible(true);
    }//GEN-LAST:event_addVideobutActionPerformed

    private void UpdateVidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateVidActionPerformed
        // TODO add your handling code here:
        UpdateFrame update = new UpdateFrame();
        update.setVisible(true);
        UpdateWhere = Videos_Table.getValueAt(Videos_Table.getSelectedRow(), 1);
        //UpdateWherePath = Videos_Table.getValueAt(Videos_Table.getSelectedRow(), 1);
    }//GEN-LAST:event_UpdateVidActionPerformed

    private void action_ChoosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_action_ChoosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_action_ChoosActionPerformed

    private void Close_LabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close_LabMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_Close_LabMouseClicked

    private void Close_LabMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close_LabMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Close_LabMouseEntered

    private void Videos_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Videos_TableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Videos_TableMouseClicked

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel VID_Table = (DefaultTableModel) Videos_Table.getModel();
        VID_Table.setRowCount(0);
        GLinkedList.GLinkedList.Node c = Link.LS.head;
        while(c != null)
        {
            String[] row = { c.VidName, c.Path, c.Action, c.PlayerName, c.Team1, c.Team2};
            VID_Table.addRow(row);
            c = c.next;
        }
        
        action_Choos.setSelectedIndex(0);
        Search_Player_Field.setText(null);
        Search_Team_Field.setText(null);
//        for(Video v : Linkedlist.ls){
//            String[] row = { v.VidName, v.Path, v.Action, v.PlayerName, v.Team1, v.Team2};
//            VID_Table.addRow(row);
//        }
    }//GEN-LAST:event_RefreshActionPerformed

    private void PlayLabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayLabMouseClicked
        // TODO add your handling code here:
        Object P = Videos_Table.getValueAt(Videos_Table.getSelectedRow(), 1);
        try {
            ProcessBuilder pd = new ProcessBuilder("C:\\Program Files\\VideoLAN\\VLC\\vlc.exe", P+".mp4");
            pd.start();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_PlayLabMouseClicked

    private void AtoZsortMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AtoZsortMouseClicked
        // TODO add your handling code here:
        
        Link.LS.ASCsortByVN();
        
        DefaultTableModel VID_Table = (DefaultTableModel) Videos_Table.getModel();
        VID_Table.setRowCount(0);
        
        GLinkedList.GLinkedList.Node c = Link.LS.head;
        
        while(c != null)
        {
            String[] row = { c.VidName, c.Path, c.Action, c.PlayerName, c.Team1, c.Team2};
            VID_Table.addRow(row);
            c = c.next;
        }
        
//        for(Video v : Linkedlist.ls){
//            String[] row = { v.VidName, v.Path, v.Action, v.PlayerName, v.Team1, v.Team2};
//            VID_Table.addRow(row);
//        }
    }//GEN-LAST:event_AtoZsortMouseClicked

    private void sortZtoAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sortZtoAMouseClicked
        // TODO add your handling code here:
        //Collections.sort(Linkedlist.ls, Collections.reverseOrder());
        Link.LS.DESsortByVN();
        DefaultTableModel VID_Table = (DefaultTableModel) Videos_Table.getModel();
        VID_Table.setRowCount(0);
        
        GLinkedList.GLinkedList.Node c = Link.LS.head;
        
        while(c != null)
        {
            String[] row = { c.VidName, c.Path, c.Action, c.PlayerName, c.Team1, c.Team2};
            VID_Table.addRow(row);
            c = c.next;
        }
        
//        for(Video v : Linkedlist.ls){
//            String[] row = { v.VidName, v.Path, v.Action, v.PlayerName, v.Team1, v.Team2};
//            VID_Table.addRow(row);
//        }        
    }//GEN-LAST:event_sortZtoAMouseClicked

    private void Search_PlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_PlayerActionPerformed
        // TODO add your handling code here:
        String PlayerN = Search_Player_Field.getText().toString();
        
        DefaultTableModel VID_Table = (DefaultTableModel) Videos_Table.getModel();
        VID_Table.setRowCount(0);
        
        GLinkedList.GLinkedList.Node c = Link.LS.head;
        
        while(c != null)
        {
            if(action_Choos.getSelectedItem().toString() != null)
            {
                if(action_Choos.getSelectedItem().toString().compareTo("Select Category") != 0)
                {
                    if(c.PlayerName.compareTo(PlayerN) == 0 && action_Choos.getSelectedItem().toString().compareTo(c.Action) == 0)
                    {
                        String[] row = { c.VidName, c.Path, c.Action, c.PlayerName, c.Team1, c.Team2};
                        VID_Table.addRow(row);
                    }
                }
                else{
                    if(c.PlayerName.compareTo(PlayerN) == 0)
                    {
                        String[] row = { c.VidName, c.Path, c.Action, c.PlayerName, c.Team1, c.Team2};
                        VID_Table.addRow(row);
                    }
                }
            }
            else{
                if(c.PlayerName.compareTo(PlayerN) == 0)
                {
                    String[] row = { c.VidName, c.Path, c.Action, c.PlayerName, c.Team1, c.Team2};
                    VID_Table.addRow(row);
                }
            }
            
            c = c.next;
        }
    }//GEN-LAST:event_Search_PlayerActionPerformed

    private void Search_TeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_TeamActionPerformed
        // TODO add your handling code here:
        String TeamN = Search_Team_Field.getText().toString();
        
        DefaultTableModel VID_Table = (DefaultTableModel) Videos_Table.getModel();
        VID_Table.setRowCount(0);
        
        GLinkedList.GLinkedList.Node c = Link.LS.head;
        
        while(c != null)
        {
            if(action_Choos.getSelectedItem().toString() != null)
            {
                if(action_Choos.getSelectedItem().toString().compareTo("Select Category") != 0)
                {
                    if((c.Team1.compareTo(TeamN) == 0 || c.Team2.compareTo(TeamN) == 0) && action_Choos.getSelectedItem().toString().compareTo(c.Action) == 0)
                    {
                        String[] row = { c.VidName, c.Path, c.Action, c.PlayerName, c.Team1, c.Team2};
                        VID_Table.addRow(row);
                    }
                }
                else{
                    if(c.Team1.compareTo(TeamN) == 0 || c.Team2.compareTo(TeamN) == 0)
                    {
                        String[] row = { c.VidName, c.Path, c.Action, c.PlayerName, c.Team1, c.Team2};
                        VID_Table.addRow(row);
                    }
                }
            }
            else{
                if(c.Team1.compareTo(TeamN) == 0 || c.Team2.compareTo(TeamN) == 0)
                {
                    String[] row = { c.VidName, c.Path, c.Action, c.PlayerName, c.Team1, c.Team2};
                    VID_Table.addRow(row);
                }
            }
            
            c = c.next;
        }
    }//GEN-LAST:event_Search_TeamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception{
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VideoPlayerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VideoPlayerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VideoPlayerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VideoPlayerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VideoPlayerGUI().setVisible(true);
            }
        });
    }
    
    void get_data(){
            try {
                //call jdbc
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                //create connection
                Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=videos;user=mahmoudd;password=123456");
                
                Statement stm = con.createStatement();
                ResultSet rs = stm.executeQuery("SELECT * FROM Video");
                
                while(rs.next())
                {
                    String VN = rs.getString("VN");
                    String P = rs.getString("P");
                    String A = rs.getString("A");
                    String PL = rs.getString("PL");
                    String T1 = rs.getString("T1");
                    String T2 = rs.getString("T2");
                    
                    Link.LS.add(VN, P, A, PL, T1, T2);
                    //Linkedlist.ls.add(new Video(VN,P,A,PL,T1,T2));
                    String VideosData[] = {VN, P, A, PL, T1, T2};
                    DefaultTableModel VID_Table = (DefaultTableModel) Videos_Table.getModel();
                    VID_Table.addRow(VideosData);
                }
                //disconnect with database
                con.close();
            }catch (ClassNotFoundException ex) {
                ex.printStackTrace();
            }
            catch (Exception ex) {
                ex.printStackTrace();
            }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddVideolab;
    private javax.swing.JLabel AtoZsort;
    private javax.swing.JLabel Chose_Category;
    private javax.swing.JLabel Close_Lab;
    private javax.swing.JButton DeleteVideobut;
    private javax.swing.JLabel DeleteVideolab;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel PlayLab;
    private javax.swing.JButton Refresh;
    private javax.swing.JScrollPane Scroll_Videos_Table;
    private javax.swing.JLabel Search_By_PlayerLab;
    private javax.swing.JLabel Search_By_TeamLab;
    private javax.swing.JButton Search_Player;
    private javax.swing.JTextField Search_Player_Field;
    private javax.swing.JButton Search_Team;
    private javax.swing.JTextField Search_Team_Field;
    private javax.swing.JLabel SortLab;
    private javax.swing.JLabel TitleLable;
    private javax.swing.JPanel TitlePanel;
    private javax.swing.JButton UpdateVid;
    private javax.swing.JLabel UpdateVideolab;
    private javax.swing.JTable Videos_Table;
    private javax.swing.JComboBox<String> action_Choos;
    private javax.swing.JButton addVideobut;
    private javax.swing.JLabel sortZtoA;
    // End of variables declaration//GEN-END:variables
}
